version: '2'
services:
  web_app:
    build: ./Dockerfile
    restart: always
    command: gunicorn -c gunicorn.conf.py app:app
    ports:
      - '5000:5000'
    volumes:
      - '/var/log/gunicorn:/var/log/gunicorn'

    mem_limit: 192m
